export const GAME_CONFIG = {
  TICK_RATE: 60,
  MAX_PLAYERS_WORLD: 50,
  MAX_PLAYERS_COMBAT: 4,
  
  WORLD: {
    WIDTH: 3200,
    HEIGHT: 2400
  },
  
  COMBAT: {
    WIDTH: 1920,
    HEIGHT: 1080,
    WAVE_INTERVAL: 20000,
    BASE_ENEMIES_PER_WAVE: 8,
    ENEMIES_PER_WAVE_INCREMENT: 5
  },
  
  PLAYER: {
    RADIUS: 26,
    BASE_SPEED: 4.5,
    RESPAWN_TIME: 5000
  },
  
  ENEMY: {
    RADIUS: 22,
    BASE_SPEED: 0.9,
    SPEED_INCREMENT_PER_WAVE: 0.07,
    BASE_HP: 40,
    HP_INCREMENT_PER_WAVE: 15,
    SPAWN_DISTANCE_MIN: 380,
    SPAWN_DISTANCE_MAX: 700
  },
  
  PROJECTILE: {
    RADIUS: 10,
    SPEED: 12,
    LIFETIME: 80
  },
  
  EXPERIENCE: {
    BASE_PER_LEVEL: 100,
    MULTIPLIER: 1.5
  }
} as const;